Initial project
bimandas1/FT2-77-Basic-PHP pull request #1
Opened 2024-02-16 11:31 UTC by bimandas1

2024-02-21 15:59 UTC, sandipta18 requested changes
1. Add an empty line at the last of each file otherwise this red circle will show.
2. There are some PHP coding standards. Please go through that and follow those coding standards while writing PHP code.

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +    $fname = $lname = $fullname = "";
Follow either camel case or snake case naming convention for declaring variables.

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +    $img_upload = false;
TRUE/FALSE should be in caps.

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +    if(isset($_POST["submit"])){
Please follow coding standards. It should be like this ->
`if (condition) {`

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +    $target_file;
Please add comment regarding the purpose for this variable

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +        if(isset($_FILES["image"]) && $_FILES["image"]["error"] == UPLOAD_ERR_OK){
Please follow coding standards.

2024-02-21 15:59 UTC, sandipta18 commented on form.php
> +            }
Please follow proper coding standards. 
And we should not write html inside PHP.

2024-02-21 15:59 UTC, sandipta18 commented on index.php
> +    <br> <br>
Why we are using `<br>` tag here?

2024-02-21 15:59 UTC, sandipta18 commented on index.php
> +            echo "<img src='$target_file' alt='Uploaded Image'> ";
We should not write html inside PHP.

2024-02-21 15:59 UTC, sandipta18 commented on index.php
> +        if($img_upload === true){
Please follow proper coding standards.

2024-02-22 06:33 UTC, sandipta18 commented
As discussed the implementation for the task 
`Full name: User cannot enter a value in Full name field. It will be disabled by default. When the first name and last name fields are filled, this field outputs the sum of the above 2 fields.` is incorrect.
So please make necessary changes.

2024-02-26 04:52 UTC, sandipta18 requested changes

2024-02-26 04:52 UTC, sandipta18 commented on creds.php
> +    $api_key = "6791558286ad4a92929083ab626e3b3c";
Keep this file in gitignore

2024-02-26 04:52 UTC, sandipta18 commented on emailValidate.php
> +    function isValidEmail($email) {
Function docblock missing

2024-02-26 04:52 UTC, sandipta18 commented on emailValidate.php
> +        // var_dump($data);
Please remove commented out code.
Do the same in all the files.

2024-02-26 04:52 UTC, sandipta18 commented on form.php
>      $firstName = $lastName = $marks_str = "";
Why are we mixing variable naming convention here? Let's either keep it `snake_case` or  `camelCase

2024-02-26 04:53 UTC, bimandas1 commented on form.php
> +    if(isset($_POST["submit"])){
Solved

2024-02-26 05:03 UTC, bimandas1 commented on emailValidate.php
> +        // var_dump($data);
solved.

2024-02-26 05:15 UTC, bimandas1 commented on form.php
>      $firstName = $lastName = $marks_str = "";
solved

2024-02-26 05:20 UTC, sandipta18 commented
No need to  push packages/libraries over github. Please keep the fpdf directory in gitignore.

2024-02-26 05:28 UTC, bimandas1 commented on creds.php
> +    $api_key = "6791558286ad4a92929083ab626e3b3c";
solved.

2024-02-26 13:38 UTC, closed without merging